/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/quanxiang-cloud/qtcc/pkg/apis/qtcc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExecutors implements ExecutorInterface
type FakeExecutors struct {
	Fake *FakeQtccV1alpha1
	ns   string
}

var executorsResource = schema.GroupVersionResource{Group: "qtcc", Version: "v1alpha1", Resource: "executors"}

var executorsKind = schema.GroupVersionKind{Group: "qtcc", Version: "v1alpha1", Kind: "Executor"}

// Get takes name of the executor, and returns the corresponding executor object, and an error if there is any.
func (c *FakeExecutors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Executor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(executorsResource, c.ns, name), &v1alpha1.Executor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Executor), err
}

// List takes label and field selectors, and returns the list of Executors that match those selectors.
func (c *FakeExecutors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExecutorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(executorsResource, executorsKind, c.ns, opts), &v1alpha1.ExecutorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExecutorList{ListMeta: obj.(*v1alpha1.ExecutorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExecutorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested executors.
func (c *FakeExecutors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(executorsResource, c.ns, opts))

}

// Create takes the representation of a executor and creates it.  Returns the server's representation of the executor, and an error, if there is any.
func (c *FakeExecutors) Create(ctx context.Context, executor *v1alpha1.Executor, opts v1.CreateOptions) (result *v1alpha1.Executor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(executorsResource, c.ns, executor), &v1alpha1.Executor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Executor), err
}

// Update takes the representation of a executor and updates it. Returns the server's representation of the executor, and an error, if there is any.
func (c *FakeExecutors) Update(ctx context.Context, executor *v1alpha1.Executor, opts v1.UpdateOptions) (result *v1alpha1.Executor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(executorsResource, c.ns, executor), &v1alpha1.Executor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Executor), err
}

// Delete takes name of the executor and deletes it. Returns an error if one occurs.
func (c *FakeExecutors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(executorsResource, c.ns, name, opts), &v1alpha1.Executor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExecutors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(executorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExecutorList{})
	return err
}

// Patch applies the patch and returns the patched executor.
func (c *FakeExecutors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Executor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(executorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Executor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Executor), err
}
